"""empty message

Revision ID: 1616b73086b3
Revises: d347d6e4b839
Create Date: 2023-11-18 16:24:56.818429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1616b73086b3'
down_revision = 'd347d6e4b839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('attack', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('defense', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('speacialAttack', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('specialDefense', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.String(), nullable=False))
        batch_op.drop_column('baseStats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseStats', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('speed')
        batch_op.drop_column('specialDefense')
        batch_op.drop_column('speacialAttack')
        batch_op.drop_column('defense')
        batch_op.drop_column('attack')
        batch_op.drop_column('hp')

    # ### end Alembic commands ###
