"""empty message

Revision ID: c938feca6e61
Revises: 1616b73086b3
Create Date: 2023-11-18 16:59:21.713838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c938feca6e61'
down_revision = '1616b73086b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speacial_Attack', sa.String(), nullable=True))
        batch_op.alter_column('specialDefense',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('speacialAttack')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speacialAttack', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('specialDefense',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('speacial_Attack')

    # ### end Alembic commands ###
